plugins:
  discourse_private_topic_enabled:
    default: false
  min_trust_to_create_tag_version:
    default: "Admin"
    enum: "TrustLevelAndStaffSetting"
  min_trust_to_create_tag_node:
    default: "Admin"
    enum: "TrustLevelAndStaffSetting"
  max_node_tags_per_topic:
    default: 5
    client: true
  max_version_tags_per_topic:
    default: 5
    client: true
